### ISSUE TITLE
Dark Mode Page Flicker

### ISSUE THREAD

**Issue by jonleopard** [jonleopard/jonleopard.com#1]
I'm noticing some strange page flicker when I leave on dark mode. It seems the state is read from localStorage and then applied resulting in a very quick (milliseconds) style change on every page load.

I've seen something similar when working with Styled-Components and SSR...so perhaps I should start there.

**Comment by jxnblk** [comment]
I believe the issue is that in order to read from `localStorage`, client-side JS is required and there's no way to know which color mode is set before JS renders. Alternative approaches could use `@media (prefers-color-scheme: dark)` or store a cookie that can be handled with server side rendering. There might be some other approaches to avoid the flicker, so I'm curious to see how you solve for this

**Comment by jonleopard** [comment]
@jxnblk  I just found a react hook for [dark mode switching](https://github.com/donavon/use-dark-mode), the author mentions having this issue as well:

> If your CSS is setup to default to light mode, but the user selects dark mode, the next time they visit your app, they will be in dark mode. However, the user will see a flash of light mode before the app is spun up and useDarkMode is called.
> 
> To prevent this, I've included some vanilla JavaScript that you can insert in your index.html just after the <body> tag. It is in a file named noflash.js.txt. You can either insert the contents of this file in a <script> tag or automate the step in your build process.
> 
> Note that if you change any of the default—such as storageKey or classNameDark for example—the noflash.js file will need to be modified with the same values.
> 
> Gatsby users may leverage gatsby-plugin-use-dark-mode to inject noflash.js for you.

So I guess I could go this route. I was just hoping to avoid installing additional dependencies for something so trivial. There's also a gatsby plugin specifically for [styled-components dark mode](https://www.gatsbyjs.org/packages/gatsby-styled-components-dark-mode/).

Still exploring what the best solution would be here.

**Comment by jxnblk** [comment]
Yup, I was just about to link to `gatsby-plugin-use-dark-mode` – you could maybe try `useLayoutEffect` during render to check the localStorage value as well

**Comment by jonleopard** [comment]
Just swapped out `useEffect` with `useLayoutEffect` and page to page transitions/loads are seamless now, so that's a definite improvement:

![Kapture 2019-05-13 at 23 03 19](https://user-images.githubusercontent.com/2111234/57653953-5d936200-75d3-11e9-8e5c-f5efb74a803f.gif)


But, there's still the issue of hard refreshing:

![Kapture 2019-05-13 at 23 05 42](https://user-images.githubusercontent.com/2111234/57654093-afd48300-75d3-11e9-91f4-7a31868dc9bb.gif)

Getting closer...
[layout.js](https://github.com/jonleopard/jonleopard.com/blob/flicker-fix/src/components/layout.js)

**Comment by mihaiserban** [comment]
I've used [gatsby-plugin-dark-mode](https://www.gatsbyjs.org/packages/gatsby-plugin-dark-mode/) for my own website https://www.mihaiserban.dev, no issues with flickering dark mode on reload.

(started as a fork from your website btw 😅, but went into a different direction with styled jsx and without rebass)

**Comment by jonleopard** [comment]
Hey @mihaiserban, nice site 😉 

I'm almost there with `useLayoutEffect` but work pulled me away from working on this more. I need to take a look at this again and see if I can fix the hard reload issue. 

Thanks for the heads up!

**Comment by jxnblk** [comment]
FWIW, if you look at the [source code](https://github.com/donavon/use-dark-mode/blob/develop/noflash.js.txt) for the `useDarkMode` hook's flash prevention, it uses some render blocking JS to prevent the flash. I think this is the best you can do to avoid the flash with statically rendered HTML. I'm looking into a solution for handling this with CSS-in-JS libraries and theme context, but don't have anything yet. If you're fine applying classnames to the body tag, this hook or the Gatsby plugin is probably your best bet
